package domain_constant

type CPOStatus int

const (
	CPO_STATUS_DRAFT CPOStatus = iota + 1
	CPO_STATUS_SUBMITTED
	CPO_STATUS_SOG_GENERATED
	CPO_STATUS_CANCELLED
	CPO_STATUS_DELETED

	SOG_STATUS_DRAFT            string = "DRAFT"
	SOG_STATUS_READY_FOR_PICK   string = "READY FOR PICK"
	SOG_STATUS_CANCELLED        string = "CANCELLED"
	SOG_FG_ITEMS_FROM_PRINCIPLE string = "Barang Principal"
	SOG_FG_ITEMS_FROM_SAMB      string = "Barang SAMB"
	SOG_FG_ITEMS_FROM_NONE      string = "None"
	SOG_EXPIRY_STATUS_OK        string = "OK"
	SOG_EXPIRY_STATUS_EXPIRED   string = "EXPIRED"

	DEFAULT_DECIMAL_PRECISION float64 = 3

	SOG_CUSTOMER_APPROVAL_STATUS_APPROVED string = "CUSTOMER APPROVED"
	SOG_CUSTOMER_APPROVAL_STATUS_WAITING  string = "WAITING CUSTOMER APPROVAL"
)
